version: '3'

services:
  redis:
    image: 'redis:8-alpine'
    container_name: redis
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5
  database:
    image: 'postgres:14.17'
    container_name: postgresql_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      retries: 5
  api:
    container_name: api
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_PORT: 5432
      CELERY_REDIS_URL: redis://redis:6379/0
      FTSESSION_S_COOKIE: ${FTSESSION_S_COOKIE}
      FTSESSION_S_COOKIE_EXPIRES: ${FTSESSION_S_COOKIE_EXPIRES}
    build:
      context: ../app
      dockerfile: 'Dockerfile'
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
  celery_worker:
    build:
      context: ../app
      dockerfile: CeleryDockerfile
    container_name: celery_worker
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - api
    environment:
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      CELERY_REDIS_URL: redis://redis:6379/0
      FTSESSION_S_COOKIE: ${FTSESSION_S_COOKIE}
      FTSESSION_S_COOKIE_EXPIRES: ${FTSESSION_S_COOKIE_EXPIRES}
  celery_beat:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A celery_app beat --loglevel=info
    depends_on:
      - celery_worker
    environment:
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      CELERY_REDIS_URL: redis://redis:6379/0
      FTSESSION_S_COOKIE: ${FTSESSION_S_COOKIE}
      FTSESSION_S_COOKIE_EXPIRES: ${FTSESSION_S_COOKIE_EXPIRES}

volumes:
  redis-data:
